# Generated by Django 2.2.15 on 2020-11-13 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='redirect_url',
            field=models.URLField(blank=True, help_text='The URL to redirect to when clicked', max_length=500, null=True),
        ),
    ]
